//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _12PMLunch.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItemMappings = new HashSet<OrderItemMapping>();
        }
    
        public int OrderId { get; set; }
        public string OrderNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int UserId { get; set; }
        public int MenuTypeId { get; set; }
        public int OrderQuantity { get; set; }
        public decimal TotalAmount { get; set; }
        public string Comments { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public int OrderStatusCode { get; set; }
    
        public virtual MenuType MenuType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemMapping> OrderItemMappings { get; set; }
        public virtual User User { get; set; }
    }
}
