//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _12PMLunch.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyQuestionRespons
    {
        public int Id { get; set; }
        public int SurveyResponseId { get; set; }
        public string QuestionUniqueId { get; set; }
        public string Question { get; set; }
        public string Response { get; set; }
        public string ResponseComments { get; set; }
    
        public virtual SurveyRespons SurveyRespons { get; set; }
    }
}
