
module.exports={
    ADD_MENU:"ADD_MENU",
    INITIALIZE_MENUS:"INITIALIZE_MENUS",
    INITIALIZE_ORDERS:"INITIALIZE_ORDERS",
    SUBMIT_ORDER:"SUBMIT_ORDER",
    SUBMIT_USER:"SUBMIT_USER",
    AUTHENTICATE_USER:"AUTHENTICATE_USER",
    SUBMIT_USERFEEDBACK:"SUBMIT_USERFEEDBACK",
    LOGIN_TOKEN:"LoginToken",
    LOGIN_TOKEN_EXPIRY:"LoginTokenExpiry",
    USER_ID:"UserId",
    EMAIL_ID:"EmailId",
    USER_ROLE:"UserRole"
}